<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Pegawai_model extends CI_Model
{

	public $table = 'pegawai';
	public $id = 'id_pegawai';
	public $order = 'DESC';

	function __construct()
	{
		parent::__construct();
	}

	// get all
	function get_all()
	{
		$this->db->order_by($this->id, $this->order);
		return $this->db->get($this->table)->result();
	}

	// get data by id
	function get_by_id($id)
	{
		$this->db->where($this->id, $id);
		return $this->db->get($this->table)->row();
	}

	// get total rows
	function total_rows($q = NULL, $onlyActive = FALSE)
	{
		$this->db->like('nama', $q);
		if ($onlyActive) {
			$this->db->where('(deleted_at IS NULL OR deleted_at = "")');
		}
		return $this->db->count_all_results($this->table);
	}

	// get data with limit and search
	public function get_limit_data($limit, $start = 0, $q = NULL, $onlyActive = FALSE)
	{
		$this->db->or_like('nama', $q);
		if ($onlyActive) {
			$this->db->where('(deleted_at IS NULL OR deleted_at = "")');
		}
		$this->db->limit($limit, $start);
		return $this->db->get($this->table)->result();
	}

	// insert data
	function insert($data)
	{
		$this->db->insert($this->table, $data);
	}

	// update data
	function update($id, $data)
	{
		$this->db->where($this->id, $id);
		$this->db->update($this->table, $data);
	}

	// delete data
	function delete($id)
	{
		$this->db->where($this->id, $id);
		$this->db->delete($this->table);
	}

	public function get_by_nip($nip)
	{
		$this->db->where('nip', $nip);
		$this->db->where('deleted_at IS NULL');
		$query = $this->db->get('pegawai');

		if ($query->num_rows() > 0) {
			return $query->row();
		} else {
			return null;
		}
	}
}

/* End of file Pegawai_model.php */
/* Location: ./application/models/Pegawai_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-03-12 07:46:51 */
/* http://harviacode.com */
