<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class User_android_model extends CI_Model
{

	public $table = 'user_android';
	public $id = 'id_user_android';
	public $order = 'DESC';

	function __construct()
	{
		parent::__construct();
	}

	// get all
	function get_all()
	{
		$this->db->order_by($this->id, $this->order);
		return $this->db->get($this->table)->result();
	}

	// get data by id
	function get_by_id($id)
	{
		$this->db->select('user_android.*, pegawai.nama');
		$this->db->from($this->table);
		$this->db->join('pegawai', 'pegawai.id_pegawai = user_android.id_pegawai', 'left');
		$this->db->where('user_android.' . $this->id, $id);
		return $this->db->get()->row();
	}

	// get total rows

	function total_rows($q = NULL, $onlyActive = FALSE)
	{
		$this->db->like('username', $q);
		if ($onlyActive) {
			$this->db->where('(deleted_at IS NULL OR deleted_at = "")');
		}
		return $this->db->count_all_results($this->table);
	}

	// get data with limit and search
	public function get_limit_data($limit, $start = 0, $q = NULL, $onlyActive = FALSE)
	{
		$this->db->select('user_android.*, pegawai.nama');
		$this->db->from($this->table);
		$this->db->join('pegawai', 'pegawai.id_pegawai = user_android.id_pegawai', 'left');

		if (!empty($q)) {
			$this->db->like('user_android.username', $q);
			$this->db->or_like('pegawai.nama', $q);
		}

		if ($onlyActive) {
			$this->db->where('(user_android.deleted_at IS NULL OR user_android.deleted_at = "")');
		}

		$this->db->order_by('pegawai.nama', 'ASC');
		$this->db->limit($limit, $start);

		return $this->db->get()->result();
	}

	// insert data
	function insert($data)
	{
		$this->db->insert($this->table, $data);
		return $this->db->insert_id();
	}

	// update data
	function update($id, $data)
	{
		$this->db->where($this->id, $id);
		$this->db->update($this->table, $data);
	}

	// delete data
	function delete($id)
	{
		$this->db->where($this->id, $id);
		$this->db->delete($this->table);
	}

	public function get_by_id_pegawai($idPegawai)
	{
		return $this->db->get_where('user_android', ['id_pegawai' => $idPegawai])->row();
	}

	public function get_by_email($email)
	{
		return $this->db->get_where('user_android', ['email' => $email])->row();
	}

	public function get_by_imei($imei)
	{
		return $this->db->get_where('user_android', ['imei' => $imei])->row();
	}

}

/* End of file User_android_model.php */
/* Location: ./application/models/User_android_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-03-12 08:02:00 */
/* http://harviacode.com */
