<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Vektor_pegawai_model extends CI_Model
{

	public $table = 'vektor_pegawai';
	public $id = 'id_vektor_pegawai';
	public $order = 'DESC';

	function __construct()
	{
		parent::__construct();
	}

	// get all
	function get_all()
	{
		$this->db->order_by($this->id, $this->order);
		return $this->db->get($this->table)->result();
	}

	// get data by id
	function get_by_id($id)
	{
		$this->db->where($this->id, $id);
		return $this->db->get($this->table)->row();
	}

	// get total rows
	function total_rows($q = NULL, $onlyActive = FALSE)
	{
		$this->db->like('id_pegawai', $q);
		if ($onlyActive) {
			$this->db->where('(deleted_at IS NULL OR deleted_at = "")');
		}
		return $this->db->count_all_results($this->table);
	}

	// get data with limit and search
	public function get_limit_data($limit, $start = 0, $q = NULL, $onlyActive = FALSE)
	{
		$this->db->select('vektor_pegawai.*, pegawai.nama');
		$this->db->from($this->table);
		$this->db->join('pegawai', 'vektor_pegawai.id_pegawai = pegawai.id_pegawai', 'left');

		if (!empty($q)) {
			$this->db->like('vektor_pegawai.id_pegawai', $q);
			$this->db->or_like('pegawai.nama', $q);
		}

		if ($onlyActive) {
			$this->db->where('(vektor_pegawai.deleted_at IS NULL OR vektor_pegawai.deleted_at = "")');
		}

		$this->db->limit($limit, $start);
		return $this->db->get()->result();
	}

	// insert data
	function insert($data)
	{
		$this->db->insert($this->table, $data);
	}

	// update data
	function update($id, $data)
	{
		$this->db->where($this->id, $id);
		$this->db->update($this->table, $data);
	}

	// delete data
	function delete($id)
	{
		$this->db->where($this->id, $id);
		$this->db->delete($this->table);
	}

}

/* End of file Vektor_pegawai_model.php */
/* Location: ./application/models/Vektor_pegawai_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-03-12 08:26:56 */
/* http://harviacode.com */
