name: Deploy API Changes to GCP

on:
  push:
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: Deploy CI3 folder
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_IP }} "
            timestamp=\$(date +%Y%m%d_%H%M%S) &&
            if [ -d /var/www/html/sipreti/uploads ]; then
              sudo mkdir -p /var/www/html/sipreti_backup &&
              sudo cp -r /var/www/html/sipreti/uploads /var/www/html/sipreti_backup/uploads_\$timestamp
            fi &&
            sudo rm -rf /tmp/deploy_ci3 &&
            mkdir -p /tmp/deploy_ci3
          "

          rsync -avz -e "ssh -o StrictHostKeyChecking=no" api/ci3/sipreti/ ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_IP }}:/tmp/deploy_ci3/

          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_IP }} "
            sudo rm -rf /var/www/html/sipreti &&
            sudo mv /tmp/deploy_ci3 /var/www/html/sipreti &&
            sudo chown -R www-data:www-data /var/www/html/sipreti
          "

      - name: Deploy Django folder
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_IP }} "sudo rm -rf /tmp/deploy_django && mkdir -p /tmp/deploy_django"
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" api/django/ ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_IP }}:/tmp/deploy_django/
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_IP }} "sudo rm -rf /var/www/html/django && sudo mv /tmp/deploy_django /var/www/html/django && sudo chown -R www-data:www-data /var/www/html/django"

      - name: Setup CI3
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_IP }} <<'EOF'
            cd /var/www/html/sipreti
            sudo /usr/local/bin/composer install --no-interaction --prefer-dist

            sudo sed -i "s|'password' => '.*'|'password' => '${{ secrets.MYSQL_ROOT_PASSWORD }}'|g" application/config/database.php

            sudo sed -i "s|\$config\['base_url'\] = .*;|\$config['base_url'] = 'http://${{ secrets.GCP_INSTANCE_IP }}/sipreti';|g" application/config/config.php

            sudo sed -i "s|fetch('http://.*:8000/attendance/face-register/|fetch('http://${{ secrets.GCP_INSTANCE_IP }}:8000/attendance/face-register/|g" application/views/vektor_pegawai/pegawai_vektor_management.php

            sudo sed -i "s|http://.*:8000|http://${{ secrets.GCP_INSTANCE_IP }}:8000|g" application/views/vektor_pegawai/pegawai_list.php

            sudo sed -i "s|http://.*:8000|http://${{ secrets.GCP_INSTANCE_IP }}:8000|g" application/views/vektor_pegawai/vektor_pegawai_list.php

            sudo sed -i "s|http://.*:8000|http://${{ secrets.GCP_INSTANCE_IP }}:8000|g" application/views/vektor_pegawai_facenet/pegawai_list.php

            sudo sed -i "s|http://.*:8000|http://${{ secrets.GCP_INSTANCE_IP }}:8000|g" application/views/vektor_pegawai_facenet/vektor_pegawai_list.php

            sudo sed -i "s|http://.*:8000|http://${{ secrets.GCP_INSTANCE_IP }}:8000|g" application/views/pegawai/pegawai_list.php
          EOF

          
      - name: Setup Django
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_IP }} '
            cd /var/www/html/django
            sudo python3.8 -m venv venv
            source venv/bin/activate

            sudo chown -R $USER:$USER /var/www/html/django/venv/
            
            pip install -r requirements.txt

            sudo mkdir -p /var/www/html/django/sipreti/assets/auth
            echo "${{ secrets.GOOGLE_DRIVE_KEY }}" | base64 -d | sudo tee /var/www/html/django/sipreti/assets/auth/credentials.json > /dev/null
          '

      - name: Configure Django settings.py
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_IP }} <<'EOF'
            sudo cp /var/www/html/django/sipreti/sipreti/settings_copy.py /var/www/html/django/sipreti/sipreti/settings.py

            sudo sed -i "s|^CI3_API_URL = .*|CI3_API_URL = \"http://${{ secrets.GCP_INSTANCE_IP }}/sipreti/vektor_pegawai/create_api\"|" /var/www/html/django/sipreti/sipreti/settings.py
            sudo sed -i "s|^CI3_API_PEGAWAI_URL = .*|CI3_API_PEGAWAI_URL = 'http://${{ secrets.GCP_INSTANCE_IP }}/sipreti/pegawai/create_api'|" /var/www/html/django/sipreti/sipreti/settings.py

            sudo sed -i "s|^SECRET_KEY = .*|SECRET_KEY = '${{ secrets.DJANGO_KEY }}'|" /var/www/html/django/sipreti/sipreti/settings.py

            sudo sed -i "s|http://localhost|http://${{ secrets.GCP_INSTANCE_IP }}|g" /var/www/html/django/sipreti/sipreti/settings.py
            sudo sed -i "s|http://127.0.0.1|http://${{ secrets.GCP_INSTANCE_IP }}|g" /var/www/html/django/sipreti/sipreti/settings.py

            sudo sed -i "s|'PASSWORD': *''|'PASSWORD': '${{ secrets.MYSQL_ROOT_PASSWORD }}'|g" /var/www/html/django/sipreti/sipreti/settings.py
          EOF


      - name: Restart sipreti service
        run: |
          ssh -o StrictHostKeyChecking=no '${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_IP }}' '
            sudo systemctl daemon-reexec
            sudo systemctl daemon-reload
            sudo systemctl restart sipreti
            sudo systemctl enable sipreti
          '
      - name: Restore uploads backup
        run: |
          ssh -o StrictHostKeyChecking=no '${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_INSTANCE_IP }}' '
            latest_backup=$(ls -dt /var/www/html/sipreti_backup/uploads_* 2>/dev/null | head -n 1)
            if [ -n "$latest_backup" ]; then
              sudo rm -rf /var/www/html/sipreti/uploads
              sudo cp -r "$latest_backup" /var/www/html/sipreti/uploads
              sudo chown -R www-data:www-data /var/www/html/sipreti/uploads
            else
              echo "Tidak ada backup uploads ditemukan."
            fi
          '